[build]
builder = "DOCKERFILE"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
# Environment variables that Railway will set
# Discord Bot Configuration
DISCORD_TOKEN = ""
DISCORD_CLIENT_ID = ""
DISCORD_CLIENT_SECRET = ""

# OpenAI Configuration  
OPENAI_API_KEY = ""
OPENAI_MODEL = "gpt-4"
OPENAI_MAX_TOKENS = "2000"

# NASA API
NASA_API_KEY = ""

# Notion Integration (Optional)
NOTION_TOKEN = ""
NOTION_DATABASE_ID = ""

# Bot Configuration
BOT_PREFIX = "!"
DEBUG_MODE = "false"
LOG_LEVEL = "INFO"
DATABASE_URL = "sqlite:///data/astra.db"

# Security
ENCRYPTION_KEY = ""
WEBHOOK_SECRET = ""

# Performance
MAX_CONCURRENT_REQUESTS = "10"
REQUEST_TIMEOUT = "30"
CACHE_TTL = "3600"

[networking]
serviceDomains = []
